service: crawler-service
frameworkVersion: ">=1.30.0"
custom:
  databucket: ${env:IMAGE_ANALYSIS_DATA_BUCKET}
  crawlerqueue: IACrawlerQueue
  analysisqueue: IAAnalysisQueue
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  accountid: ${env:AWS_ACCOUNT_ID}

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.databucket}/*"
    - Effect: Allow
      Action:
        - sqs:ListQueues
      Resource: "arn:aws:sqs:${self:provider.region}:*:*"
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
      Resource: "arn:aws:sqs:*:*:${self:custom.crawlerqueue}"
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
      Resource: "arn:aws:sqs:*:*:${self:custom.analysisqueue}"

functions:
  crawlImages:
    handler: handler.crawlImages
    role: arn:aws:iam::${self:custom.accountid}:role/image-analysis
    environment:
      DATA_BUCKET: ${self:custom.databucket}
      ANALYSIS_QUEUE: ${self:custom.analysisqueue}
      REGION: ${self:custom.region}
      ACCOUNTID: ${self:custom.accountid}
    events:
      - sqs:
          arn: "arn:aws:sqs:${self:provider.region}:${self:custom.accountid}:${self:custom.crawlerqueue}"
