AWSTemplateFormatVersion: 2010-09-09

Description: Asset and Logging Buckets

Parameters:
  DataExchange:
    Description: Data Exchange 
    Type: String
    ConstraintDescription: Data Exchange
  RetentionPeriodDays:
    Type: Number
    Description: Specify the number of days to retain log files (e.g. 730)
    Default: 730

Resources:
  ManifestBucketLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - !Sub ${DataExchange}
          - !Ref "AWS::AccountId"
          -
            Fn::Sub:
              ${AWS::Region}
          - "manifest"
          - "logs"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref RetentionPeriodDays
            Id: Object expiration policy
            Status: Enabled
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled

  AssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - !Sub ${DataExchange}
          - !Ref "AWS::AccountId"
          -
            Fn::Sub:
              ${AWS::Region}
          - "asset"
      BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref AssetBucketLoggingBucket
        LogFilePrefix: !Join
          - "-"
          - - !Sub s3-access-logs/${DataExchange}
            - !Ref "AWS::AccountId"
            -
              Fn::Sub:
                ${AWS::Region}/
            - "asset"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled

  AssetBucketLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - !Sub ${DataExchange}
          - !Ref "AWS::AccountId"
          -
            Fn::Sub:
              ${AWS::Region}
          - "asset"
          - "logs"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref RetentionPeriodDays
            Id: Object expiration policy
            Status: Enabled
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled

Outputs: 
  ManifestBucket:
    Description: Manifest Bucket
    Value: !Join
        - "-"
        - - !Sub ${DataExchange}
          - !Ref "AWS::AccountId"
          -
            Fn::Sub:
              ${AWS::Region}
          - "manifest"
  ManifestBucketLoggingBucket:
    Description: Manifest Bucket Logging Bucket
    Value: !Ref ManifestBucketLoggingBucket
  ManifestBucketLoggingBucketArn:
    Description: Manifest Bucket Logging Bucket ARN
    Value: !GetAtt ManifestBucketLoggingBucket.Arn
  ManifestBucketLoggingPrefix: 
    Description: Manifest Bucket Logging Prefix
    Value: !Join
          - "-"
          - - !Sub s3-access-logs/${DataExchange}
            - !Ref "AWS::AccountId"
            -
              Fn::Sub:
                ${AWS::Region}/
            - "manifest"
  AssetBucket:
    Description: Asset Bucket
    Value: !Ref AssetBucket
  AssetBucketArn:
    Description: Asset Bucket ARN
    Value: !GetAtt AssetBucket.Arn
  AssetBucketLoggingBucket:
    Description: Asset Bucket Logging Bucket
    Value: !Ref AssetBucketLoggingBucket
  AssetBucketLoggingBucketArn:
    Description: Asset Bucket Logging Bucket ARN
    Value: !GetAtt AssetBucketLoggingBucket.Arn

