AWSTemplateFormatVersion: 2010-09-09

Description: Web Server in us-east-1

Parameters:
  AmiId:
    Description: The ID of the AMI.
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    ConstraintDescription: The ID of the AMI.
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  InstanceName:
    Description: EC2 Instance Name (ideally globally unique)
    Type: String
    ConstraintDescription: EC2 Instance Name (ideally globally unique)
  KeyPair:
    Description: SSH KeyPair Name
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Provide the name of an existing SSH key pair
    Default: 'wangrob-ec2-us-east-1'

Resources:
  WSInstanceSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub ${InstanceName}-sg
      GroupDescription: Web server instance security group
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  Ec2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - arn:aws:iam::aws:policy/AmazonDocDBFullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - Ref: Ec2InstanceRole

  WSInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref IamInstanceProfile
      ImageId: !Ref AmiId
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - Ref: WSInstanceSG
      Tags:
        - Key: Name
          Value: !Ref InstanceName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Print out timestamp
          cd /home/ec2-user/
          whoami > whoami.txt
          date > timestamps.txt
          # install and start Apache
          yum update -y
          yum install -y httpd
          cd /var/www/html
          echo "<html><h1>Hello World from ${InstanceName}.</h1></html>" > index.html
          service httpd start
          chkconfig httpd on
          # Print out timestamp
          cd /home/ec2-user/
          date >> timestamps.txt
          # install CloudWatch monitoring scripts
          yum install -y perl-Switch perl-DateTime perl-Sys-Syslog perl-LWP-Protocol-https perl-Digest-SHA.x86_64
          curl https://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.2.zip -O
          unzip CloudWatchMonitoringScripts-1.2.2.zip
          rm -rf CloudWatchMonitoringScripts-1.2.2.zip
          # Print out timestamp
          cd /home/ec2-user/
          date >> timestamps.txt

  WSInstanceEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref WSInstance

Outputs: 
  WSInstanceId:
    Description: Web Server Instance Id
    Value: !Ref WSInstance
  WSInstanceIP:
    Description: Web Server Instance EIP
    Value: !Ref WSInstanceEIP

