service: hello-serverless
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2

functions:
  helloServerless:
    handler: handler.helloServerless
    events:
      - http:
          path: say/helloServerless
          method: get
 